version: 2.1
orbs:
  # orgs contain basc recipes and reproducible actions (install node, aws, etc.)
  node: circleci/node@4.1.0
  eb: circleci/aws-elastic-beanstalk@1.0.0
  aws-cli: circleci/aws-cli@2.0.2
  # different jobs are calles later in the workflows sections
jobs:
  build:
    docker:
      # the base image can run most needed actions with orbs
      - image: "cimg/base:stable"
    steps:
      - node/install
      - checkout
      - aws-cli/setup
      - eb/setup
      # install dependencies in both apps
      - run:
          name: Install Front-End Dependencies
          command: npm run frontend:install
      - run:
          name: Install API Dependencies
          command: npm run backend:install
      - run:
          name: Build The UI
          command: npm run frontend:build
      - run:
          name: Build The Server
          command: npm run backend:build
      - run:
          name: Front-End Deploy
          command: npm run frontend:deploy
      - run:
          name: The Server Delopy
          command: npm run backend:deploy
workflows:
  main: # workflow label
    jobs:
      - build:
          filters:
            branches:
              only:
                - main
